root
 |-- product_asin: string (nullable = true)
 |-- sentence_text: string (nullable = true)
 |-- helpfulness_score: double (nullable = true)
 |-- product_image_url: string (nullable = true)
 |-- product_name: string (nullable = true)
 |-- review_length: integer (nullable = true)
 |-- word_count: integer (nullable = true)
 |-- helpfulness_band: string (nullable = false)
 |-- ingestion_source: string (nullable = false)
 |-- ingestion_timestamp: timestamp (nullable = false)
 |-- is_very_short: integer (nullable = false)
 |-- is_very_long: integer (nullable = false)
 |-- has_low_detail: integer (nullable = false)